org.gradle.jvmargs=-Xmx2048M
archives_base_name=default-server-properties

mod_id=dsp
mod_version=26.1.0.2
maven_group=dev.nanite.mods

minecraft_version=26.1
minecraft_version_range=[26.1,26.2)
minecraft_version_range_semver=>=26.1

neoforge_version=26.1.0.8-beta
neoforge_version_range=[26.1,27.0)

fabric_loader_version=0.18.4
fabric_api_version=0.144.0+26.1

curseforge_id=676811
modrinth_id=Fnrzx9Jl
github_repo=nanite/Default-Server-Properties

