org.gradle.jvmargs=-Xmx2048M
archives_base_name=default-server-properties

mod_id=dsp
mod_version=26.2.0.2
maven_group=dev.nanite.mods

minecraft_version=26.2
minecraft_version_range=[26.2,27.0)
minecraft_version_range_semver=>=26.2

neoforge_version=26.2.0.7-beta
neoforge_version_range=[26.2.0.0,27.0.0.0)

fabric_loader_version=0.19.3
fabric_api_version=0.153.0+26.2

curseforge_id=676811
modrinth_id=Fnrzx9Jl
github_repo=nanite/Default-Server-Properties

