modLoader = "javafml"
loaderVersion = "[40,)"
license = "All rights reserved"
issueTrackerURL="https://github.com/nanite/Default-Server-Properties/issues"

[[mods]]
modId = "dsp"
displayURL="https://github.com/nanite/Default-Server-Properties"
version = "${version}"
displayName = "Default Server Properties"
description = '''
Simple mod that allows modpack developers to define a default server properties file. This is typically used for settings like the default_level_type.
'''
displayTest="IGNORE_ALL_VERSION"

[[dependencies.dsp]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "SERVER"

# And another dependency, use this if you want to require a certain Minecraft version.
[[dependencies.dsp]]
modId = "minecraft"
mandatory = true
# See above for how to read this notation, this essentially means any
# version of Minecraft from 1.18.2 (inclusive).
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
