name: Build & Release

on:
  push:
    tags:
      - 'release/**/*'

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    uses: nanite/workflows/.github/workflows/release.yml@v1.2
    with:
      gradle-tasks: 'build publish publishMods'
      java-version: '21'
    secrets:
      nanite-token: ${{ secrets.NANITE_DEPLOY }}
      curse-token: ${{ secrets.CURSE_DEPLOY }}
      modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
